services:

  platformstore:
    image: platformstore
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT: "8888"
      SPRING_APPLICATION_NAME: platformstore
      SPRING_PROFILES_ACTIVE: "default"
    depends_on:
      eurekaserver:
        condition: service_started
      configserver:
        condition: service_started
      

    networks:
      backend:
        aliases:
          - "platformstore"

  configserver:
    image: configserver
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/Vl4ddd/platfrom-store-properties"
      SPRING_CLOUD_CONFIG_SERVER_GIT_BRANCH: "main"
    networks:
      backend:
        aliases:
          - "configserver"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 5

  eurekaserver:
    image: eurekaserver
    ports:
      - "8761:8761"
    depends_on:
      configserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "eurekaserver"


  gatewayserver:
    image: gatewayserver
    ports:
      - "8072:8072"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8072"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKASERVER_PORT: "8888"
      CONFIGSERVER_PORT: "8761"
    depends_on:
      configserver:
        condition: service_started
      eurekaserver:
        condition: service_started
    networks:
      backend:
        aliases:
          - "gateway"

networks:
  backend:
    driver: bridge
