version: '3.8'

services:
  platformstore:
    image: platformstore
    ports:
      - "8080:8080"
    environment:
      PROFILE: "defolt"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      SPRING_APPLICATION_NAME: platformstore
      SPRING_PROFILES_ACTIVE: "defolt"
      

    networks:
        backend:
          aliases:
            - "platformstore"
  
  configserver:
      image: configserver
      ports:
        - "8888:8888"
      environment:
          ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
          SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/Vl4ddd/platfrom-store-properties"  
          SPRING_CLOUD_CONFIG_SERVER_GIT_BRANCH: "main"
          
      networks:
          backend:
            aliases:
              - "configserver"

networks:
  backend:
    driver: bridge